### ISSUE TITLE
Change the name to something much better =P

### ISSUE THREAD

**Issue by jni** [hmaarrfk/wabisabi#15]
* Deprecation Factory version: Any
* Python version: Any
* Operating System: Any

### Description

For the library name, I humbly suggest `wabisabi`. From [Wikipedia](https://en.wikipedia.org/wiki/Wabi-sabi):

> In traditional Japanese aesthetics, wabi-sabi (侘寂) is a world view centered on the acceptance of transience and imperfection.

### What I Did

It came to me in a dream.

**Comment by hmaarrfk** [comment]
I actually really like the intro paragraph to wikipedia.

Do you have any source where I can learn more about this philosophy? I just want to make sure I don't adopt a terribly horrible philosophy

**Comment by jni** [comment]
@hmaarrfk I don't have a comprehensive source, but nothing I have read about it (only bits and pieces) suggests horribleness. I think it is pretty safe to adopt. =)
